server:
  port: 8080

spring:
  application:
    name: ai-customer-service
  cloud:
    alibaba:
      ai:
        dashscope:
          api-key: sk-e75a3809f1fb484392ad899228e5947b
          model: qwen-turbo
          temperature: 0.7
          max-tokens: 1000
          top-p: 1.0
          enable-logging: true
          logging-level: DEBUG
          enable-metrics: true
          enable-functions: true
          enable-streaming: true
          client:
            connect-timeout: 30000
            read-timeout: 60000
        wanx:
          api-key: sk-e75a3809f1fb484392ad899228e5947b
          model: wanx-v1
          enable-logging: true
          logging-level: DEBUG
          client:
            connect-timeout: 30000
            read-timeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.agent: DEBUG
    org.springframework.web: DEBUG
    com.alibaba.cloud: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

